// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkThemeSwitch: typeof import('./components/DarkThemeSwitch/DarkThemeSwitch.vue')['default']
    MenuSearch: typeof import('./components/MenuSearch/MenuSearch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowColumnTree: typeof import('./components/TableNext/components/ShowColumnTree.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    TableColumn: typeof import('./components/TableNext/components/TableColumn.vue')['default']
    TableNext: typeof import('./components/TableNext/TableNext.vue')['default']
  }
}

export {}
